nelmio_api_doc:
    documentation:
        info:
            title: PublicSquare
            description: PublicSquare Implementation API Docs
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!.*(/doc|/{index}|/contexts|/doc.json)) # Accepts routes under /api except /api/doc
